apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ep-healthcheck
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
  - patch
---    
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ep-healthcheck
