apiVersion: v1
kind: Service
metadata:
  name: __APP__-nodeport
  labels:
    app: __APP__
spec:
  selector:    
    app: __APP__
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
