apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ep-healthcheck
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
  - patch
---    
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ep-healthcheck
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ep-healthcheck-rw
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ep-healthcheck
subjects:
- kind: ServiceAccount
  name: ep-healthcheck
  namespace: __NAMESPACE__
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-ep-healthcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      run: k8s-ep-healthcheck
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: k8s-ep-healthcheck
    spec:
      containers:
      - name: k8s-ep-healthcheck
        image: __IMAGE__
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "0.5"
            memory: "500Mi"
          requests:
            cpu: "0.3"
            memory: "200Mi"
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ep-healthcheck
      serviceAccountName: ep-healthcheck
      terminationGracePeriodSeconds: 30
